language: 
  - swift
osx_image: 
  - xcode10.2
xcode_workspace: 
  - "MealMe.xcworkspace" # path to your xcodeproj folder
xcode_scheme: 
  - "MealMeTests"
destination: 
  - "platform=iOS Simulator,OS=11.3,name=iPhone X"
