language: 
  - swift
osx_image: 
  - xcode10.2
xcode_xcworkspace: 
  - MealMe.xcworkspace # path to your xcodeproj folder
xcode_scheme: 
  - MealMe
destination: 
  - "platform=iOS Simulator,OS=11.3,name=iPhone X"
before_install:
  - pod install --repo-update

