language: 
  - swift
osx_image: 
  - xcode10.2
xcode_project: 
  - MealMe.xcodeproj # path to your xcodeproj folder
xcode_scheme: 
  - "MealMeTests"
destination: 
  - "platform=iOS Simulator,OS=11.3,name=iPhone X"
