language: 
  - swift
osx_image: 
  - xcode10.2
#xcode_xcworkspace: 
 # - MealMe.xcworkspace # path to your xcodeproj folder
#xcode_scheme: 
 # - MealMe
#destination: 
 # - "platform=iOS Simulator,OS=11.3,name=iPhone X"
before_install:
  - pod install --repo-update
script:
    - xcodebuild clean -project MealMe.xcodeproj -scheme MealMe -destination "platform:iOS Simulator, id:B3A5F3C8-0AD6-43A1-BDB1-31A5F12448A6, OS:12.2, name:iPhone X" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO -quiet
