language: 
  - swift
osx_image: 
  - xcode10.2
before_install:
  - pod install --repo-update
script:
    - xcodebuild clean -project MealMe.xcodeproj -scheme MealMe -destination "platform=iOS Simulator,name=iPhone X,OS=12.2" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO -quiet
script:
    - xcodebuild test -project MealMe.xcodeproj -scheme MealMeTests -destination "platform=iOS Simulator,name=iPhone X,OS=12.2" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO -quiet
